In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('aggs').getOrCreate()

In [3]:
df = spark.read.csv('/FileStore/tables/sales_info.csv',inferSchema = True,
                    header = True)

In [4]:
df.show()

In [5]:
df.printSchema()

In [6]:
df.groupby("Company").min().show()

In [7]:
df.agg({'Sales': 'sum'}).collect()[0].asDict()

In [8]:
group_data = df.groupby('Company')

In [9]:
group_data.agg({'Sales': 'min'}).show()

In [10]:
from pyspark.sql.functions import *

In [11]:
a = df.select(stddev('Sales').alias('std'))
a.select(format_number('std',2).alias('std')).show()

In [12]:
df.orderBy(df['Sales'].desc()).show()